spring:
  application:
    name: bank-application
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-application-database
    username: postgres
    password: Krantik@123
    driver-class-name: org.postgresql.Driver
  flyway:
      clean-on-validation-error: 'true'
      baseline-on-migrate: 'true'
      enabled: 'true'
      locations: classpath:db/migration
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: transactionExchange
          content-type: application/json


